#include<iostream>
using namespace std;
/* templates are important in cpp
templates class-object 
object-templates
63 is all about how the templates are used like template is used like declaring a T by any data type like
 you can use it as int float char void and any other data t type so we dont havto create many nore 
 classes for each data type
 Template T;
 class vector{
     int varaible;
 }



*/
int main(){

return 0;
}